name: Build iOS and Android App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS (.ipa)
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS App Bundle
        run: flutter build ios --release --no-codesign

      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-runner
          path: build/ios/iphoneos/Runner.app

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --no-tree-shake-icons

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
